// ============================================================
// GAME DATA - All static game constants and content
// ============================================================

const TYRE_COMPOUNDS = {
  soft: {
    id: 'soft', name: 'Soft', abbr: 'S', color: '#FF3333', bg: '#3a0000',
    baseGrip: 1.00, wearRate: 1.8, warmupLaps: 1,
    optimalTemp: 92, tempRange: [80, 110],
    cliffPoint: 60, postCliffMult: 2.5,
    minLaps: 10, maxLaps: 22,
    wetPenalty: 0.40,
  },
  medium: {
    id: 'medium', name: 'Medium', abbr: 'M', color: '#FFEE00', bg: '#2a2a00',
    baseGrip: 0.97, wearRate: 1.1, warmupLaps: 2,
    optimalTemp: 85, tempRange: [75, 105],
    cliffPoint: 75, postCliffMult: 2.0,
    minLaps: 18, maxLaps: 38,
    wetPenalty: 0.35,
  },
  hard: {
    id: 'hard', name: 'Hard', abbr: 'H', color: '#EEEEEE', bg: '#1a1a1a',
    baseGrip: 0.94, wearRate: 0.65, warmupLaps: 3,
    optimalTemp: 78, tempRange: [70, 100],
    cliffPoint: 88, postCliffMult: 1.8,
    minLaps: 28, maxLaps: 60,
    wetPenalty: 0.40,
  },
  inter: {
    id: 'inter', name: 'Intermediate', abbr: 'I', color: '#00CC44', bg: '#002200',
    baseGrip: 0.88, wearRate: 0.5, warmupLaps: 1,
    optimalTemp: 45, tempRange: [20, 70],
    cliffPoint: 80, postCliffMult: 1.5,
    minLaps: 15, maxLaps: 50,
    wetBonus: 0.15, dryPenalty: 0.20,
  },
  wet: {
    id: 'wet', name: 'Full Wet', abbr: 'W', color: '#3399FF', bg: '#000033',
    baseGrip: 0.82, wearRate: 0.3, warmupLaps: 1,
    optimalTemp: 28, tempRange: [10, 50],
    cliffPoint: 85, postCliffMult: 1.4,
    minLaps: 20, maxLaps: 80,
    wetBonus: 0.28, dryPenalty: 0.45,
  }
};

const TRACKS = [
  {
    id: 'bahrain', name: 'Bahrain Grand Prix', circuit: 'Bahrain International Circuit',
    emoji: '🇧🇭', laps: 57, lapLength: 5.412, pitlaneTime: 22,
    type: 'starter', tier: 1,
    characteristics: { tyreStress: 0.75, downforce: 0.60, power: 0.70, braking: 0.65, heat: 0.85 },
    weather: { baseTemp: 32, variance: 6, rainChance: 0.04, rainIntensity: 0.3 },
    tyreMult: { soft: 1.25, medium: 1.10, hard: 1.00 },
    drsZones: 3, safetyCarChance: 0.18,
    description: 'Abrasive desert surface punishes tyres. Long straights reward power.',
    baseReward: { money: 12000, cardSlots: 2 },
    eventPool: ['brake_wear', 'engine_heat', 'safety_car', 'tire_strategy', 'engine_mode'],
  },
  {
    id: 'saudi', name: 'Saudi Arabian Grand Prix', circuit: 'Jeddah Corniche Circuit',
    emoji: '🇸🇦', laps: 50, lapLength: 6.174, pitlaneTime: 24,
    type: 'high_speed', tier: 1,
    characteristics: { tyreStress: 0.50, downforce: 0.55, power: 0.85, braking: 0.70, heat: 0.75 },
    weather: { baseTemp: 29, variance: 4, rainChance: 0.02, rainIntensity: 0.2 },
    tyreMult: { soft: 1.10, medium: 1.05, hard: 1.00 },
    drsZones: 3, safetyCarChance: 0.35,
    description: 'Ultra-fast street circuit. Crashes are likely. DRS crucial.',
    baseReward: { money: 15000, cardSlots: 2 },
    eventPool: ['safety_car', 'wall_contact', 'drs_failure', 'engine_mode', 'narrow_escape'],
  },
  {
    id: 'australia', name: 'Australian Grand Prix', circuit: 'Albert Park Circuit',
    emoji: '🇦🇺', laps: 58, lapLength: 5.278, pitlaneTime: 20,
    type: 'balanced', tier: 1,
    characteristics: { tyreStress: 0.55, downforce: 0.65, power: 0.65, braking: 0.60, heat: 0.55 },
    weather: { baseTemp: 22, variance: 8, rainChance: 0.20, rainIntensity: 0.6 },
    tyreMult: { soft: 1.05, medium: 1.00, hard: 0.95 },
    drsZones: 4, safetyCarChance: 0.22,
    description: 'Semi-street circuit. Unpredictable weather can transform the race.',
    baseReward: { money: 13000, cardSlots: 2 },
    eventPool: ['rain_shower', 'safety_car', 'driver_error', 'tire_strategy', 'engine_mode'],
  },
  {
    id: 'japan', name: 'Japanese Grand Prix', circuit: 'Suzuka International Racing Course',
    emoji: '🇯🇵', laps: 53, lapLength: 5.807, pitlaneTime: 23,
    type: 'technical', tier: 2,
    characteristics: { tyreStress: 0.65, downforce: 0.85, power: 0.60, braking: 0.75, heat: 0.60 },
    weather: { baseTemp: 20, variance: 10, rainChance: 0.35, rainIntensity: 0.8 },
    tyreMult: { soft: 1.15, medium: 1.05, hard: 0.98 },
    drsZones: 2, safetyCarChance: 0.25,
    description: 'Technical masterpiece. High downforce needed. Rain is a wild card.',
    baseReward: { money: 16000, cardSlots: 3 },
    eventPool: ['rain_shower', 'tire_strategy', 'safety_car', 'suspension_damage', 'driver_error'],
  },
  {
    id: 'monaco', name: 'Monaco Grand Prix', circuit: 'Circuit de Monaco',
    emoji: '🇲🇨', laps: 78, lapLength: 3.337, pitlaneTime: 26,
    type: 'street', tier: 2,
    characteristics: { tyreStress: 0.40, downforce: 0.90, power: 0.40, braking: 0.85, heat: 0.50 },
    weather: { baseTemp: 24, variance: 7, rainChance: 0.18, rainIntensity: 0.7 },
    tyreMult: { soft: 0.95, medium: 0.98, hard: 1.00 },
    drsZones: 1, safetyCarChance: 0.40,
    description: 'Impossible to overtake. Qualifying and pit stop timing is everything.',
    baseReward: { money: 22000, cardSlots: 3 },
    eventPool: ['safety_car', 'wall_contact', 'rain_shower', 'narrow_escape', 'pit_stop_drama', 'brake_wear'],
  },
  {
    id: 'spain', name: 'Spanish Grand Prix', circuit: 'Circuit de Barcelona-Catalunya',
    emoji: '🇪🇸', laps: 66, lapLength: 4.657, pitlaneTime: 21,
    type: 'balanced', tier: 2,
    characteristics: { tyreStress: 0.70, downforce: 0.70, power: 0.65, braking: 0.65, heat: 0.72 },
    weather: { baseTemp: 26, variance: 6, rainChance: 0.10, rainIntensity: 0.5 },
    tyreMult: { soft: 1.20, medium: 1.08, hard: 1.00 },
    drsZones: 2, safetyCarChance: 0.15,
    description: 'The upgrade race. Hard on tyres, great for testing new parts.',
    baseReward: { money: 14000, cardSlots: 2 },
    eventPool: ['brake_wear', 'tire_strategy', 'upgrade_opportunity', 'engine_mode', 'safety_car'],
  },
  {
    id: 'silverstone', name: 'British Grand Prix', circuit: 'Silverstone Circuit',
    emoji: '🇬🇧', laps: 52, lapLength: 5.891, pitlaneTime: 22,
    type: 'high_speed', tier: 2,
    characteristics: { tyreStress: 0.65, downforce: 0.75, power: 0.70, braking: 0.60, heat: 0.55 },
    weather: { baseTemp: 18, variance: 12, rainChance: 0.40, rainIntensity: 0.9 },
    tyreMult: { soft: 1.10, medium: 1.05, hard: 1.00 },
    drsZones: 2, safetyCarChance: 0.20,
    description: 'Home of British F1. Fast sweeping corners. Infamous British weather.',
    baseReward: { money: 18000, cardSlots: 3 },
    eventPool: ['rain_shower', 'tire_strategy', 'safety_car', 'driver_error', 'engine_mode'],
  },
  {
    id: 'monza', name: 'Italian Grand Prix', circuit: 'Autodromo Nazionale Monza',
    emoji: '🇮🇹', laps: 53, lapLength: 5.793, pitlaneTime: 23,
    type: 'power', tier: 3,
    characteristics: { tyreStress: 0.45, downforce: 0.30, power: 0.95, braking: 0.80, heat: 0.65 },
    weather: { baseTemp: 25, variance: 8, rainChance: 0.22, rainIntensity: 0.7 },
    tyreMult: { soft: 1.00, medium: 0.98, hard: 0.95 },
    drsZones: 3, safetyCarChance: 0.28,
    description: 'Temple of Speed. Lowest downforce. Engine is king. Slipstreaming battles.',
    baseReward: { money: 20000, cardSlots: 3 },
    eventPool: ['engine_mode', 'slipstream_battle', 'safety_car', 'rain_shower', 'brake_failure'],
  },
  {
    id: 'singapore', name: 'Singapore Grand Prix', circuit: 'Marina Bay Street Circuit',
    emoji: '🇸🇬', laps: 62, lapLength: 4.940, pitlaneTime: 28,
    type: 'street', tier: 3,
    characteristics: { tyreStress: 0.60, downforce: 0.80, power: 0.55, braking: 0.80, heat: 0.90 },
    weather: { baseTemp: 31, variance: 5, rainChance: 0.30, rainIntensity: 0.9 },
    tyreMult: { soft: 1.05, medium: 1.00, hard: 0.97 },
    drsZones: 3, safetyCarChance: 0.45,
    description: 'Night race. Extreme heat and humidity. Safety car almost guaranteed.',
    baseReward: { money: 21000, cardSlots: 3 },
    eventPool: ['safety_car', 'rain_shower', 'wall_contact', 'engine_heat', 'narrow_escape', 'pit_stop_drama'],
  },
  {
    id: 'abudhabi', name: 'Abu Dhabi Grand Prix', circuit: 'Yas Marina Circuit',
    emoji: '🇦🇪', laps: 58, lapLength: 5.281, pitlaneTime: 22,
    type: 'season_finale', tier: 4,
    characteristics: { tyreStress: 0.55, downforce: 0.65, power: 0.75, braking: 0.65, heat: 0.70 },
    weather: { baseTemp: 28, variance: 4, rainChance: 0.03, rainIntensity: 0.2 },
    tyreMult: { soft: 1.05, medium: 1.00, hard: 0.98 },
    drsZones: 2, safetyCarChance: 0.20,
    description: 'Season finale. Everything on the line. Twilight to night race.',
    baseReward: { money: 30000, cardSlots: 4 },
    eventPool: ['tire_strategy', 'engine_mode', 'safety_car', 'championship_pressure', 'final_push'],
  },
];

// Driver stats: skill = race pace (60-100), qualifying = single-lap pace, rain = wet weather
const AI_TEAMS = [
  {
    id: 'red_bull', name: 'Oracle Red Bull Racing', shortName: 'Red Bull',
    color: '#1E41FF', logoEmoji: '🐂',
    carStrength: 88, pitSpeed: 95, strategySkill: 90, budget: 'top',
    carStats: { speed: 84, downforce: 76, reliability: 76, pitSpeed: 95 },
    startMoney: 70000, difficulty: 'easy',
    description: 'Verstappen is the best on the grid. Your advantage is immense — but Hadjar needs development.',
    startingDeck: ['undercut', 'overcut', 'push_mode', 'tire_wizard', 'safety_car_prep', 'engine_mode_push', 'bold_overtake', 'ers_deploy'],
    drivers: [
      { name: 'Verstappen', number: 1,  skill: 99, qualifying: 98, rain: 97 },
      { name: 'Hadjar',     number: 6,  skill: 77, qualifying: 79, rain: 73 },
    ],
  },
  {
    id: 'mclaren', name: 'McLaren F1 Team', shortName: 'McLaren',
    color: '#FF8000', logoEmoji: '🟠',
    carStrength: 90, pitSpeed: 88, strategySkill: 84, budget: 'top',
    carStats: { speed: 82, downforce: 80, reliability: 78, pitSpeed: 88 },
    startMoney: 70000, difficulty: 'easy',
    description: 'The reigning pace-setters. Norris and Piastri give you two genuine title contenders.',
    startingDeck: ['undercut', 'overcut', 'push_mode', 'tire_wizard', 'safety_car_prep', 'engine_mode_push', 'bold_overtake', 'ers_deploy'],
    drivers: [
      { name: 'Norris',  number: 4,  skill: 92, qualifying: 91, rain: 86 },
      { name: 'Piastri', number: 81, skill: 88, qualifying: 87, rain: 83 },
    ],
  },
  {
    id: 'ferrari', name: 'Scuderia Ferrari', shortName: 'Ferrari',
    color: '#DC0000', logoEmoji: '🐎',
    carStrength: 87, pitSpeed: 88, strategySkill: 80, budget: 'top',
    carStats: { speed: 80, downforce: 82, reliability: 74, pitSpeed: 88 },
    startMoney: 70000, difficulty: 'easy',
    description: "Leclerc's qualifying pace plus Hamilton's wet-weather genius. Stunning potential.",
    startingDeck: ['undercut', 'overcut', 'push_mode', 'tire_wizard', 'safety_car_prep', 'engine_mode_push', 'bold_overtake', 'ers_deploy'],
    drivers: [
      { name: 'Leclerc',  number: 16, skill: 92, qualifying: 96, rain: 84 },
      { name: 'Hamilton', number: 44, skill: 91, qualifying: 87, rain: 96 },
    ],
  },
  {
    id: 'mercedes', name: 'Mercedes-AMG Petronas', shortName: 'Mercedes',
    color: '#00D2BE', logoEmoji: '⭐',
    carStrength: 85, pitSpeed: 92, strategySkill: 88, budget: 'top',
    carStats: { speed: 78, downforce: 78, reliability: 82, pitSpeed: 92 },
    startMoney: 70000, difficulty: 'easy',
    description: 'A technical powerhouse rebuilt for the new regulations. Russell leads, Antonelli learns fast.',
    startingDeck: ['undercut', 'overcut', 'push_mode', 'tire_wizard', 'safety_car_prep', 'engine_mode_push', 'bold_overtake', 'ers_deploy'],
    drivers: [
      { name: 'Russell',   number: 63, skill: 86, qualifying: 89, rain: 80 },
      { name: 'Antonelli', number: 12, skill: 79, qualifying: 83, rain: 75 },
    ],
  },
  {
    id: 'aston', name: 'Aston Martin Aramco', shortName: 'Aston Martin',
    color: '#006F62', logoEmoji: '🟢',
    carStrength: 76, pitSpeed: 83, strategySkill: 80, budget: 'mid',
    carStats: { speed: 68, downforce: 70, reliability: 72, pitSpeed: 83 },
    startMoney: 50000, difficulty: 'hard',
    description: "Alonso's genius can drag this car beyond its limits. Stroll's inconsistency is your biggest internal rival.",
    startingDeck: ['undercut', 'push_mode', 'tyre_management_mode', 'sponsor_deal', 'fresh_front_wing', 'drs_assist'],
    drivers: [
      { name: 'Alonso', number: 14, skill: 90, qualifying: 84, rain: 89 },
      { name: 'Stroll', number: 18, skill: 71, qualifying: 70, rain: 72 },
    ],
  },
  {
    id: 'williams', name: 'Williams Racing', shortName: 'Williams',
    color: '#005AFF', logoEmoji: '💙',
    carStrength: 73, pitSpeed: 78, strategySkill: 72, budget: 'mid',
    carStats: { speed: 64, downforce: 68, reliability: 70, pitSpeed: 78 },
    startMoney: 42000, difficulty: 'medium',
    description: 'Sainz has transformed this team. A genuine mid-pack threat with room to grow.',
    startingDeck: ['undercut', 'overcut', 'push_mode', 'tyre_management_mode', 'fresh_front_wing', 'bold_overtake', 'ers_deploy'],
    drivers: [
      { name: 'Sainz', number: 55, skill: 87, qualifying: 86, rain: 83 },
      { name: 'Albon', number: 23, skill: 82, qualifying: 80, rain: 79 },
    ],
  },
  {
    id: 'alpine', name: 'BWT Alpine F1 Team', shortName: 'Alpine',
    color: '#0090FF', logoEmoji: '🔷',
    carStrength: 71, pitSpeed: 80, strategySkill: 74, budget: 'mid',
    carStats: { speed: 62, downforce: 66, reliability: 72, pitSpeed: 80 },
    startMoney: 40000, difficulty: 'medium',
    description: "Gasly's experience anchors the team. Colapinto adds flair but needs careful management.",
    startingDeck: ['undercut', 'overcut', 'push_mode', 'tyre_management_mode', 'fresh_front_wing', 'bold_overtake', 'ers_deploy'],
    drivers: [
      { name: 'Gasly',     number: 10, skill: 81, qualifying: 81, rain: 77 },
      { name: 'Colapinto', number: 43, skill: 75, qualifying: 77, rain: 73 },
    ],
  },
  {
    id: 'racing_bulls', name: 'Visa Cash App RB', shortName: 'Racing Bulls',
    color: '#6692FF', logoEmoji: '⚡',
    carStrength: 69, pitSpeed: 79, strategySkill: 72, budget: 'lower',
    carStats: { speed: 60, downforce: 62, reliability: 68, pitSpeed: 79 },
    startMoney: 38000, difficulty: 'medium',
    description: 'Lawson is proven, Lindblad is raw talent. Every point is a battle.',
    startingDeck: ['undercut', 'overcut', 'push_mode', 'tyre_management_mode', 'fresh_front_wing', 'bold_overtake', 'ers_deploy'],
    drivers: [
      { name: 'Lawson',   number: 30, skill: 76, qualifying: 74, rain: 72 },
      { name: 'Lindblad', number: 40, skill: 72, qualifying: 74, rain: 68 },
    ],
  },
  {
    id: 'haas', name: 'MoneyGram Haas F1 Team', shortName: 'Haas',
    color: '#B6BABD', logoEmoji: '🦅',
    carStrength: 65, pitSpeed: 76, strategySkill: 68, budget: 'lower',
    carStats: { speed: 57, downforce: 59, reliability: 65, pitSpeed: 76 },
    startMoney: 35000, difficulty: 'medium',
    description: 'Ocon brings F1 experience; Bearman brings energy. Every card in your deck will matter.',
    startingDeck: ['undercut', 'overcut', 'push_mode', 'tyre_management_mode', 'fresh_front_wing', 'bold_overtake', 'ers_deploy'],
    drivers: [
      { name: 'Ocon',    number: 31, skill: 80, qualifying: 78, rain: 81 },
      { name: 'Bearman', number: 38, skill: 77, qualifying: 76, rain: 74 },
    ],
  },
  {
    id: 'audi', name: 'Audi F1 Team', shortName: 'Audi',
    color: '#C0C0C0', logoEmoji: '🔘',
    carStrength: 68, pitSpeed: 74, strategySkill: 67, budget: 'lower',
    carStats: { speed: 59, downforce: 61, reliability: 62, pitSpeed: 74 },
    startMoney: 38000, difficulty: 'medium',
    description: 'New money, new team. Hülkenberg can punch above weight. Bortoleto has raw potential.',
    startingDeck: ['undercut', 'overcut', 'push_mode', 'tyre_management_mode', 'fresh_front_wing', 'bold_overtake', 'ers_deploy'],
    drivers: [
      { name: 'Hülkenberg', number: 27, skill: 83, qualifying: 84, rain: 80 },
      { name: 'Bortoleto',  number: 5,  skill: 75, qualifying: 77, rain: 72 },
    ],
  },
  {
    id: 'cadillac', name: 'Cadillac F1 Team', shortName: 'Cadillac',
    color: '#0033A0', logoEmoji: '🇺🇸',
    carStrength: 62, pitSpeed: 70, strategySkill: 64, budget: 'lower',
    carStats: { speed: 52, downforce: 54, reliability: 58, pitSpeed: 70 },
    startMoney: 30000, difficulty: 'hard',
    description: 'The American dream. Rock bottom of the grid — Bottas and Pérez know how to score points.',
    startingDeck: ['undercut', 'push_mode', 'tyre_management_mode', 'sponsor_deal', 'fresh_front_wing', 'drs_assist'],
    drivers: [
      { name: 'Bottas', number: 77, skill: 80, qualifying: 79, rain: 78 },
      { name: 'Pérez',  number: 11, skill: 78, qualifying: 76, rain: 74 },
    ],
  },
];

// Available drivers for custom team selection (reserves + F2 drivers)
const DRIVER_POOL = [
  { name: 'Tsunoda',       number: 22, skill: 79, qualifying: 81, rain: 75, cost: 18000, tier: 'F1 Reserve', bio: 'Ex-Racing Bulls. 5 F1 seasons of experience.' },
  { name: 'M. Schumacher', number: 47, skill: 75, qualifying: 74, rain: 78, cost: 14000, tier: 'F1 Reserve', bio: 'Mercedes reserve. Son of a legend.' },
  { name: 'Doohan',        number: 61, skill: 74, qualifying: 75, rain: 70, cost: 12000, tier: 'F1 Reserve', bio: 'Ex-Alpine. Fast qualifier, Australian talent.' },
  { name: 'de Vries',      number: 21, skill: 73, qualifying: 72, rain: 74, cost: 11000, tier: 'F1 Reserve', bio: 'Formula E champion. Ex-AlphaTauri.' },
  { name: 'Crawford',      number: 20, skill: 73, qualifying: 75, rain: 67, cost: 10000, tier: 'F2',         bio: 'Red Bull junior. F2 frontrunner.' },
  { name: 'Aron',          number: 50, skill: 72, qualifying: 74, rain: 70, cost:  9000, tier: 'F2',         bio: 'Estonian talent. Multiple F2 wins.' },
  { name: 'Drugovich',     number: 80, skill: 72, qualifying: 73, rain: 69, cost:  9000, tier: 'F2',         bio: '2022 F2 Champion. Aston Martin reserve.' },
  { name: 'Martins',       number: 25, skill: 71, qualifying: 73, rain: 68, cost:  8000, tier: 'F2',         bio: 'French Alpine junior.' },
  { name: 'Maloney',       number: 45, skill: 70, qualifying: 71, rain: 69, cost:  7000, tier: 'F2',         bio: 'Barbadian racer. Strong overtaker.' },
  { name: 'Maini',         number: 29, skill: 70, qualifying: 70, rain: 71, cost:  6000, tier: 'F2',         bio: 'Experienced F2 campaigner.' },
  { name: 'Verschoor',     number: 17, skill: 68, qualifying: 69, rain: 66, cost:  5000, tier: 'F2',         bio: 'Dutch veteran of the F2 field.' },
  { name: 'Hauger',        number: 9,  skill: 67, qualifying: 70, rain: 65, cost:  4500, tier: 'F2',         bio: 'Norwegian talent. Red Bull junior.' },
];

// ============================================================
// CARDS
// ============================================================
const ALL_CARDS = [
  // === STRATEGY CARDS ===
  {
    id: 'undercut', name: 'Undercut', type: 'strategy', rarity: 'common',
    color: '#FF8C00', icon: '↙',
    description: 'Pit one lap before your rival. Emerge on fresh tyres ahead.',
    effect: 'pit_advantage',
    value: 8, // seconds gained if successful
    uses: 1, timing: 'pit_window',
    flavorText: '"The undercut always works." — Unknown Strategist',
    tags: ['pit', 'position'],
  },
  {
    id: 'overcut', name: 'Overcut', type: 'strategy', rarity: 'common',
    color: '#FF8C00', icon: '↗',
    description: 'Stay out and build a gap. Pit after your rival on older but warm tyres.',
    effect: 'pit_advantage_late',
    value: 6,
    uses: 1, timing: 'pit_window',
    flavorText: '"Sometimes patience is the fastest strategy."',
    tags: ['pit', 'position'],
  },
  {
    id: 'safety_car_prep', name: 'Safety Car Prep', type: 'strategy', rarity: 'uncommon',
    color: '#FFD700', icon: '🔮',
    description: 'Perfect pit stop timing under the safety car. Free pit stop, no time lost.',
    effect: 'free_pit',
    value: 25,
    uses: 1, timing: 'safety_car',
    flavorText: '"We saw it coming. The data never lies." — Race Engineer',
    tags: ['pit', 'safety_car', 'timing'],
  },
  {
    id: 'double_stack', name: 'Double Stack', type: 'strategy', rarity: 'rare',
    color: '#FF4500', icon: '⚡',
    description: 'Pit both cars simultaneously. Risky but can leapfrog multiple rivals.',
    effect: 'double_pit_advantage',
    value: 12,
    uses: 1, timing: 'pit_window',
    flavorText: '"Trust the process." — Red Bull Pit Wall',
    tags: ['pit', 'team'],
  },
  {
    id: 'aggressive_strategy', name: 'Three-Stop Aggressive', type: 'strategy', rarity: 'uncommon',
    color: '#FF6600', icon: '🔥',
    description: 'Run an extra pit stop on fresh softs. Huge speed but risky timing.',
    effect: 'aggressive_stint',
    value: 10,
    uses: 1, timing: 'any',
    flavorText: '"We go hunting. Soft tyres all the way." — Strategist',
    tags: ['tyres', 'aggressive'],
  },
  // === TECHNICAL CARDS ===
  {
    id: 'fresh_front_wing', name: 'Fresh Front Wing', type: 'technical', rarity: 'common',
    color: '#4488FF', icon: '🔧',
    description: 'Swap to a new front wing at next pit stop. Restores full downforce.',
    effect: 'fix_damage',
    statBoost: { downforce: 15 },
    uses: 1, timing: 'pit_stop',
    flavorText: '"We have a wing on standby." — Mechanic',
    tags: ['damage', 'setup'],
  },
  {
    id: 'tire_wizard', name: 'Tyre Wizard', type: 'technical', rarity: 'uncommon',
    color: '#4488FF', icon: '🧙',
    description: 'Reduce tyre wear rate by 25% for this stint. Extend your strategy.',
    effect: 'reduce_wear',
    value: 0.25,
    uses: 1, timing: 'any',
    flavorText: '"Gentlemen, we are managing the tyres." — Hamilton, circa 2012',
    tags: ['tyres', 'management'],
  },
  {
    id: 'brake_duct_upgrade', name: 'Brake Duct Upgrade', type: 'technical', rarity: 'uncommon',
    color: '#4488FF', icon: '❄️',
    description: 'Cool the brakes down. Prevent brake wear events for 15 laps.',
    effect: 'prevent_brake_event',
    value: 15,
    uses: 1, timing: 'any',
    flavorText: '"Temperature nominal. We are good." — Engineer',
    tags: ['brakes', 'prevention'],
  },
  {
    id: 'engine_mode_push', name: 'Party Mode', type: 'technical', rarity: 'rare',
    color: '#8844FF', icon: '💜',
    description: 'Unlock maximum engine mode. -0.4s/lap for 8 laps. Engine life risk.',
    effect: 'engine_push',
    value: { speed: 0.4, laps: 8, reliability_risk: 0.15 },
    uses: 1, timing: 'any',
    flavorText: '"It\'s party time. Mode 11." — Verstappen',
    tags: ['engine', 'speed', 'risk'],
  },
  {
    id: 'drs_assist', name: 'DRS Harvest', type: 'technical', rarity: 'common',
    color: '#4488FF', icon: '📡',
    description: 'Maximize DRS usage this lap. Gain 0.3s per DRS zone available.',
    effect: 'drs_boost',
    value: 0.3,
    uses: 3, timing: 'any',
    flavorText: '"Activate DRS as early as possible." — Race Engineer',
    tags: ['drs', 'speed'],
  },
  {
    id: 'ers_deploy', name: 'Full ERS Deploy', type: 'technical', rarity: 'uncommon',
    color: '#44DDFF', icon: '⚡',
    description: 'Deploy all stored ERS energy at once. Massive one-lap boost.',
    effect: 'ers_boost',
    value: 0.6,
    uses: 1, timing: 'any',
    flavorText: '"Harvest done. Deploy everything." — Energy Manager',
    tags: ['ers', 'overtake'],
  },
  // === DRIVER CARDS ===
  {
    id: 'push_mode', name: 'Push Mode', type: 'driver', rarity: 'common',
    color: '#FF3333', icon: '🏎',
    description: 'Driver pushes flat out. -0.5s/lap for 5 laps, +30% tyre wear.',
    effect: 'driver_push',
    value: { speed: 0.5, laps: 5, wear_mult: 1.3 },
    uses: 1, timing: 'any',
    flavorText: '"I feel good. Let me push." — Driver',
    tags: ['speed', 'tyres', 'driver'],
  },
  {
    id: 'tyre_management_mode', name: 'Manage Tyres', type: 'driver', rarity: 'common',
    color: '#AAFFAA', icon: '🐢',
    description: 'Conserve tyres heavily. +0.8s/lap but extend stint by 6 laps.',
    effect: 'tyre_conserve',
    value: { speed: -0.8, wear_reduction: 0.4 },
    uses: 1, timing: 'any',
    flavorText: '"Box, box. No, stay out. Stay out." — Strategy',
    tags: ['tyres', 'conservation'],
  },
  {
    id: 'bold_overtake', name: 'Bold Move', type: 'driver', rarity: 'uncommon',
    color: '#FF3333', icon: '⚔️',
    description: 'Attempt an audacious overtake. 70% chance to gain 2 positions, 30% to lose 1.',
    effect: 'risky_overtake',
    value: { success_chance: 0.70, gain: 2, penalty: 1 },
    uses: 1, timing: 'race',
    flavorText: '"We go for it. Nothing to lose." — Driver Radio',
    tags: ['overtake', 'risk'],
  },
  {
    id: 'defensive_masterclass', name: 'Defensive Masterclass', type: 'driver', rarity: 'uncommon',
    color: '#FF7744', icon: '🛡',
    description: 'Hold position for 5 laps against faster rivals behind you.',
    effect: 'hold_position',
    value: 5,
    uses: 1, timing: 'race',
    flavorText: '"I am keeping him behind. Don\'t worry." — Alonso, every race',
    tags: ['defence', 'position'],
  },
  {
    id: 'qualifying_lap', name: 'Magic Lap', type: 'driver', rarity: 'rare',
    color: '#FFD700', icon: '✨',
    description: 'Driver finds an extraordinary qualifying lap. Gain 3 grid positions.',
    effect: 'quali_boost',
    value: 3,
    uses: 1, timing: 'qualifying',
    flavorText: '"That was a lap from another planet." — Commentator',
    tags: ['qualifying', 'position'],
  },
  // === WILDCARD / EVENT CARDS ===
  {
    id: 'safety_car_call', name: 'Deploy Safety Car', type: 'wildcard', rarity: 'uncommon',
    color: '#FFDD00', icon: '🚗',
    description: 'Trigger a safety car period. Use with Safety Car Prep for maximum effect.',
    effect: 'trigger_safety_car',
    value: 1,
    uses: 1, timing: 'race',
    flavorText: '"Car stopped on track. Safety car deployed." — Race Control',
    tags: ['safety_car', 'chaos'],
  },
  {
    id: 'rain_dance', name: 'Rain Dance', type: 'wildcard', rarity: 'rare',
    color: '#4488FF', icon: '🌧',
    description: 'Force a rain shower. If you have inters fitted, gain 4+ positions.',
    effect: 'trigger_rain',
    value: { rain_chance: 0.85, intensity: 0.7 },
    uses: 1, timing: 'race',
    flavorText: '"Team Chaos checking in. Bring the rain." — Unknown',
    tags: ['weather', 'chaos'],
  },
  {
    id: 'sponsor_deal', name: 'Emergency Sponsorship', type: 'wildcard', rarity: 'common',
    color: '#00AA44', icon: '💰',
    description: 'Activate sponsor deal. Gain $8,000 bonus prize money this race.',
    effect: 'money_bonus',
    value: 8000,
    uses: 1, timing: 'any',
    flavorText: '"Great exposure! The logo was on screen for 3 full minutes." — PR Team',
    tags: ['money', 'sponsor'],
  },
  {
    id: 'recovery_mode', name: 'Recovery Mode', type: 'wildcard', rarity: 'uncommon',
    color: '#FF8844', icon: '🔄',
    description: 'After any disaster, recover 3 positions over next 10 laps.',
    effect: 'recovery',
    value: 3,
    uses: 1, timing: 'after_event',
    flavorText: '"We\'ve been here before. Keep your head down and push." — Engineer',
    tags: ['recovery', 'position'],
  },
  // === PERMANENT / UPGRADE CARDS ===
  {
    id: 'wind_tunnel_data', name: 'Wind Tunnel Data', type: 'upgrade', rarity: 'uncommon',
    color: '#AA88FF', icon: '📊',
    description: 'Permanent: +3 to car downforce stat. Better cornering all season.',
    effect: 'permanent_upgrade',
    statBoost: { downforce: 3 },
    uses: 1, timing: 'between_races', permanent: true,
    flavorText: '"The correlation between tunnel and track is finally working." — Aero',
    tags: ['upgrade', 'permanent', 'downforce'],
  },
  {
    id: 'engine_upgrade', name: 'Engine Upgrade', type: 'upgrade', rarity: 'rare',
    color: '#FF4444', icon: '🔩',
    description: 'Permanent: +4 to car speed stat. Faster on straights all season.',
    effect: 'permanent_upgrade',
    statBoost: { speed: 4 },
    uses: 1, timing: 'between_races', permanent: true,
    flavorText: '"The new spec arrived. We should be 0.3 seconds faster." — PU Engineer',
    tags: ['upgrade', 'permanent', 'engine'],
  },
  {
    id: 'reliability_package', name: 'Reliability Package', type: 'upgrade', rarity: 'uncommon',
    color: '#44AAFF', icon: '🔒',
    description: 'Permanent: +5 reliability. Reduce DNF chance all season.',
    effect: 'permanent_upgrade',
    statBoost: { reliability: 5 },
    uses: 1, timing: 'between_races', permanent: true,
    flavorText: '"We reinforced the failure point. Should never happen again." — Chief Mechanic',
    tags: ['upgrade', 'permanent', 'reliability'],
  },
  {
    id: 'pitstop_training', name: 'Pit Stop Training', type: 'upgrade', rarity: 'uncommon',
    color: '#FFAA44', icon: '⏱',
    description: 'Permanent: -1.2 seconds from all pit stop times.',
    effect: 'permanent_upgrade',
    statBoost: { pitSpeed: 5 },
    uses: 1, timing: 'between_races', permanent: true,
    flavorText: '"Practice makes perfect. 2.0 second stops, consistently." — Pit Crew Chief',
    tags: ['upgrade', 'permanent', 'pit'],
  },
  {
    id: 'data_analysis', name: 'Advanced Data Analysis', type: 'upgrade', rarity: 'rare',
    color: '#AA88FF', icon: '🧮',
    description: 'Permanent: See rival strategies 2 laps in advance during races.',
    effect: 'strategy_vision',
    uses: 1, timing: 'between_races', permanent: true,
    flavorText: '"Our prediction model has 94% accuracy." — Data Scientist',
    tags: ['upgrade', 'permanent', 'strategy'],
  },
];

// ============================================================
// RACE EVENTS
// ============================================================
const RACE_EVENTS = [
  {
    id: 'safety_car', name: 'Safety Car Deployed!',
    icon: '🚗', severity: 'medium',
    description: 'A car has stopped on track. Safety car is out. Pit lane is open.',
    trigger: 'random',
    choices: [
      {
        id: 'pit_now', label: 'Pit immediately',
        description: 'Box now for fresh tyres under SC. Lose ~5s but gain grip.',
        outcome: { position_change: 0, tyre_change: true, time_penalty: 5, note: 'Pitted under SC' },
        cardSynergy: ['safety_car_prep', 'double_stack'],
      },
      {
        id: 'stay_out', label: 'Stay out',
        description: 'Maintain position. Rivals who pit may leapfrog you on restart.',
        outcome: { position_change: 1, tyre_change: false, note: 'Stayed out, track position kept' },
        cardSynergy: ['overcut'],
      },
    ],
  },
  {
    id: 'rain_shower', name: 'Rain Starting!',
    icon: '🌧', severity: 'high',
    description: 'Rain is falling on part of the track. It\'s getting heavy. What tyres?',
    trigger: 'weather',
    choices: [
      {
        id: 'pit_inters', label: 'Pit for Intermediates',
        description: 'Safe choice in light/medium rain. Lose time in pits.',
        outcome: { tyre_change: true, new_tyre: 'inter', time_penalty: 22, note: 'Pitted for inters' },
        cardSynergy: ['rain_dance'],
      },
      {
        id: 'stay_slicks', label: 'Stay on slicks',
        description: 'Gamble that rain stays light. Risk +5s/lap if it gets heavier.',
        outcome: { risk: 'heavy_rain_penalty', gamble_bonus: 8, note: 'Gambling on slicks' },
        cardSynergy: [],
      },
      {
        id: 'pit_wets', label: 'Pit for Full Wets',
        description: 'If it gets very heavy, full wets will dominate.',
        outcome: { tyre_change: true, new_tyre: 'wet', time_penalty: 22, note: 'Pitted for full wets' },
        cardSynergy: ['rain_dance'],
      },
    ],
  },
  {
    id: 'brake_wear', name: 'Brake Wear Warning!',
    icon: '🔥', severity: 'medium',
    description: 'Engineer: "Brakes are getting very hot. We may have a problem in 8 laps."',
    trigger: 'mechanical',
    choices: [
      {
        id: 'brake_bias', label: 'Adjust brake bias',
        description: 'Move brake bias to rear. +0.3s/lap but save the brakes.',
        outcome: { speed_penalty: 0.3, prevents: 'brake_failure', note: 'Adjusted brake bias' },
        cardSynergy: ['brake_duct_upgrade'],
      },
      {
        id: 'push_through', label: 'Push through it',
        description: '60% chance brakes hold. 40% chance of brake failure and DNF.',
        outcome: { risk: 'dnf', risk_chance: 0.40, speed_penalty: 0, note: 'Pushing through brake issue' },
        cardSynergy: ['push_mode'],
      },
      {
        id: 'early_pit', label: 'Pit early',
        description: 'Early stop for fresh setup. Safe but costs 8+ seconds to rivals.',
        outcome: { tyre_change: true, time_penalty: 8, prevents: 'brake_failure', note: 'Early pit for brakes' },
        cardSynergy: ['undercut'],
      },
    ],
  },
  {
    id: 'engine_mode', name: 'Engine Mode Decision',
    icon: '⚡', severity: 'low',
    description: 'Race engineer: "We have fuel to play with. Which mode do you want?"',
    trigger: 'strategy',
    choices: [
      {
        id: 'max_attack', label: 'Max Attack mode',
        description: '-0.5s/lap for 6 laps. Increases engine wear slightly.',
        outcome: { speed_bonus: 0.5, duration: 6, reliability_risk: 0.05, note: 'Max Attack mode' },
        cardSynergy: ['engine_mode_push'],
      },
      {
        id: 'standard', label: 'Standard mode',
        description: 'Stay on current settings. Consistent and safe.',
        outcome: { speed_bonus: 0, note: 'Maintained standard mode' },
        cardSynergy: [],
      },
      {
        id: 'charge_ers', label: 'Harvest ERS',
        description: 'Slow down to recharge. +0.2s/lap now, -0.5s burst later.',
        outcome: { speed_penalty: 0.2, ers_charge: 1.0, note: 'Harvesting ERS for later' },
        cardSynergy: ['ers_deploy'],
      },
    ],
  },
  {
    id: 'tire_strategy', name: 'Tyre Strategy Fork',
    icon: '🔄', severity: 'low',
    description: 'Your tyres are at 55% wear. Engineer sees two strategy options.',
    trigger: 'strategy',
    choices: [
      {
        id: 'push_for_end', label: 'Push for fastest laps',
        description: 'Extract max pace now. Tyres may cliff before the end.',
        outcome: { speed_bonus: 0.4, wear_increase: 0.3, cliff_risk: true, note: 'Pushing for fastest laps' },
        cardSynergy: ['push_mode'],
      },
      {
        id: 'nurse_to_end', label: 'Nurse to the finish',
        description: 'Baby the tyres. +0.3s/lap but guarantee no cliff.',
        outcome: { speed_penalty: 0.3, wear_reduction: 0.4, note: 'Nursing tyres to finish' },
        cardSynergy: ['tyre_management_mode', 'tire_wizard'],
      },
    ],
  },
  {
    id: 'drs_failure', name: 'DRS Failure!',
    icon: '📡', severity: 'medium',
    description: 'DRS is stuck open/closed! We need to fix it or race without.',
    trigger: 'mechanical',
    choices: [
      {
        id: 'pit_fix', label: 'Pit to fix DRS',
        description: 'Stop for ~8 seconds to fix DRS. Rejoin lower but with full car.',
        outcome: { tyre_change: false, time_penalty: 8, fixes: 'drs', note: 'Pitted to fix DRS' },
        cardSynergy: [],
      },
      {
        id: 'race_without', label: 'Race without DRS',
        description: 'Stuck closed: +0.6s on straights. Stuck open: risk wing damage.',
        outcome: { speed_penalty: 0.6, risk: 'wing_damage', note: 'Racing without DRS' },
        cardSynergy: ['ers_deploy'],
      },
    ],
  },
  {
    id: 'wall_contact', name: 'Wall Contact!',
    icon: '💥', severity: 'high',
    description: 'Driver clipped the barrier! Front wing is damaged. What\'s the call?',
    trigger: 'incident',
    choices: [
      {
        id: 'pit_new_wing', label: 'Pit for new wing',
        description: 'Stop for fresh front wing. Safe but very costly in time.',
        outcome: { tyre_change: true, time_penalty: 15, fixes: 'wing_damage', note: 'Pitted for new wing' },
        cardSynergy: ['fresh_front_wing'],
      },
      {
        id: 'push_on', label: 'Push on with damage',
        description: '50% chance it holds. 50% chance of failure: 20s+ time loss.',
        outcome: { risk: 'wing_failure', risk_chance: 0.50, speed_penalty: 0.4, note: 'Racing with damage' },
        cardSynergy: ['recovery_mode'],
      },
    ],
  },
  {
    id: 'slipstream_battle', name: 'Slipstream Battle!',
    icon: '💨', severity: 'low',
    description: 'You\'re in a DRS train. Three cars wheel-to-wheel on the straight!',
    trigger: 'racing',
    choices: [
      {
        id: 'attack_outside', label: 'Attack on outside',
        description: 'Bold move around the outside. 65% chance to gain 1 position.',
        outcome: { risk: 'position_gamble', success: { position_change: 1 }, fail: { position_change: -1 }, success_chance: 0.65, note: 'Attacked on outside' },
        cardSynergy: ['bold_overtake', 'ers_deploy'],
      },
      {
        id: 'defensive_line', label: 'Defend position',
        description: 'Focus on keeping what you have. Solid but no gain.',
        outcome: { position_change: 0, note: 'Held defensive line' },
        cardSynergy: ['defensive_masterclass'],
      },
      {
        id: 'wait_for_corner', label: 'Wait for braking zone',
        description: 'Save the move for the hairpin. 80% success, lower risk.',
        outcome: { risk: 'position_gamble', success: { position_change: 1 }, fail: { position_change: 0 }, success_chance: 0.80, note: 'Attacked at hairpin' },
        cardSynergy: ['bold_overtake'],
      },
    ],
  },
  {
    id: 'suspension_damage', name: 'Suspension Issue!',
    icon: '⚠️', severity: 'high',
    description: 'Vibration through the wheel. Could be nothing. Could be critical.',
    trigger: 'mechanical',
    choices: [
      {
        id: 'pit_immediately', label: 'Pit immediately',
        description: 'Don\'t risk it. Safe retirement prevention.',
        outcome: { tyre_change: true, time_penalty: 12, prevents: 'dnf', note: 'Cautious pit for check' },
        cardSynergy: [],
      },
      {
        id: 'push_two_laps', label: 'Push for 2 more laps',
        description: 'Hold position for 2 laps then pit when it suits strategy.',
        outcome: { risk: 'suspension_failure', risk_chance: 0.30, delay_laps: 2, note: 'Pushed 2 more laps' },
        cardSynergy: ['recovery_mode'],
      },
      {
        id: 'ignore_it', label: 'Ignore it, push on',
        description: '40% DNF risk but could finish in current position.',
        outcome: { risk: 'dnf', risk_chance: 0.40, speed_penalty: 0, note: 'Ignoring vibration' },
        cardSynergy: [],
      },
    ],
  },
  {
    id: 'championship_pressure', name: 'Championship Moment!',
    icon: '🏆', severity: 'medium',
    description: 'Your rival for the title is 5 seconds behind on faster tyres. He\'s coming.',
    trigger: 'championship',
    choices: [
      {
        id: 'defend_hard', label: 'Defend the championship',
        description: 'Take aggressive defensive lines. Protect at all costs.',
        outcome: { position_held: true, tyre_wear_increase: 0.2, note: 'Defended championship position' },
        cardSynergy: ['defensive_masterclass', 'push_mode'],
      },
      {
        id: 'set_fastest_lap', label: 'Set fastest lap',
        description: 'Push for the extra point. May lose position but score fastest lap bonus.',
        outcome: { fastest_lap: true, position_risk: true, note: 'Pushed for fastest lap bonus' },
        cardSynergy: ['push_mode', 'ers_deploy'],
      },
    ],
  },
  {
    id: 'narrow_escape', name: 'Near Miss!',
    icon: '😱', severity: 'medium',
    description: 'Your driver narrowly avoided a spinning car. Adrenaline is high!',
    trigger: 'incident',
    choices: [
      {
        id: 'stay_focused', label: 'Stay focused',
        description: 'Calm the driver down. May cost +0.2s/lap for 3 laps.',
        outcome: { speed_penalty: 0.2, duration: 3, note: 'Staying composed after near miss' },
        cardSynergy: [],
      },
      {
        id: 'use_adrenaline', label: 'Use the adrenaline',
        description: 'Channel it! -0.5s/lap for 3 laps, but risky.',
        outcome: { speed_bonus: 0.5, duration: 3, risk: 'mistake', risk_chance: 0.20, note: 'Riding the adrenaline' },
        cardSynergy: ['push_mode'],
      },
    ],
  },
  {
    id: 'pit_stop_drama', name: 'Pit Stop Drama!',
    icon: '🔩', severity: 'high',
    description: 'A wheel nut isn\'t going on! Driver waiting in box. Clock ticking.',
    trigger: 'mechanical',
    choices: [
      {
        id: 'wait_it_out', label: 'Wait for proper fit',
        description: 'Take the time penalty. Safe re-entry but very slow stop (8+ sec).',
        outcome: { pit_time_extra: 8, prevents: 'loose_wheel', note: 'Waited for safe wheel fix' },
        cardSynergy: ['pitstop_training'],
      },
      {
        id: 'release_risky', label: 'Release early (risky)',
        description: '70% chance wheel holds. 30% chance of loose wheel, black flag.',
        outcome: { risk: 'loose_wheel_dnf', risk_chance: 0.30, pit_time_extra: 0, note: 'Risky early release' },
        cardSynergy: [],
      },
    ],
  },
  {
    id: 'driver_error', name: 'Driver Error!',
    icon: '🌀', severity: 'medium',
    description: 'Driver ran wide and lost 3 seconds. He\'s apologising on the radio.',
    trigger: 'incident',
    choices: [
      {
        id: 'calm_down', label: 'Calm him down',
        description: 'Tell him it\'s fine. Consistent laps from here.',
        outcome: { position_change: 0, note: 'Calmed driver, steady laps ahead' },
        cardSynergy: [],
      },
      {
        id: 'push_harder', label: 'Push harder to recover',
        description: 'Drive lap of his life for 5 laps. Risky but may recover time.',
        outcome: { speed_bonus: 0.4, duration: 5, wear_increase: 0.2, note: 'Pushing hard to recover' },
        cardSynergy: ['push_mode'],
      },
    ],
  },
  {
    id: 'engine_heat', name: 'Engine Temperature Critical!',
    icon: '🌡', severity: 'high',
    description: 'Engine temp is hitting red. Singapore heat is unbearable tonight.',
    trigger: 'mechanical',
    choices: [
      {
        id: 'reduce_power', label: 'Reduce engine mode',
        description: 'Turn down the engine. +0.5s/lap but protect the engine.',
        outcome: { speed_penalty: 0.5, prevents: 'engine_failure', note: 'Engine mode reduced' },
        cardSynergy: [],
      },
      {
        id: 'push_and_hope', label: 'Push and hope',
        description: '35% chance of engine failure DNF. But you could hold position.',
        outcome: { risk: 'engine_dnf', risk_chance: 0.35, note: 'Gambling with engine temp' },
        cardSynergy: ['reliability_package'],
      },
    ],
  },
  {
    id: 'upgrade_opportunity', name: 'Data Windfall!',
    icon: '📈', severity: 'low',
    description: 'Engineers have found a setup that suits this track perfectly.',
    trigger: 'engineering',
    choices: [
      {
        id: 'implement_now', label: 'Implement for this race',
        description: 'Gain -0.4s/lap for the rest of the race.',
        outcome: { speed_bonus: 0.4, note: 'Setup change implemented' },
        cardSynergy: ['wind_tunnel_data'],
      },
      {
        id: 'save_for_quali', label: 'Save for next qualifying',
        description: 'Bank the data. Gain 2 grid positions next qualifying session.',
        outcome: { future_quali_bonus: 2, note: 'Data saved for next qualifying' },
        cardSynergy: ['data_analysis'],
      },
    ],
  },
  {
    id: 'final_push', name: 'Final 10 Laps!',
    icon: '🏁', severity: 'low',
    description: 'Last 10 laps. What\'s your final strategy call?',
    trigger: 'endgame',
    choices: [
      {
        id: 'absolute_attack', label: 'Absolute Attack',
        description: 'Everything left in the tank. Push driver and car to the limit.',
        outcome: { speed_bonus: 0.6, wear_increase: 0.4, risk: 'mistake', risk_chance: 0.15, note: 'Absolute attack - final laps' },
        cardSynergy: ['push_mode', 'engine_mode_push', 'ers_deploy'],
      },
      {
        id: 'controlled_finish', label: 'Controlled Finish',
        description: 'Bring it home cleanly. No mistakes, protect the result.',
        outcome: { speed_bonus: 0, risk: null, note: 'Controlled to the flag' },
        cardSynergy: ['tyre_management_mode'],
      },
    ],
  },
  {
    id: 'brake_failure', name: 'Total Brake Failure!',
    icon: '💣', severity: 'critical',
    description: 'Complete brake failure on Turn 1! Driver managed to get it stopped. Miraculous escape.',
    trigger: 'mechanical',
    choices: [
      {
        id: 'retire_safely', label: 'Retire the car',
        description: 'Driver safety first. DNF but full reliability bonus next race.',
        outcome: { dnf: true, reliability_bonus: 10, note: 'Retired safely - brake failure' },
        cardSynergy: ['reliability_package'],
      },
      {
        id: 'limp_to_pits', label: 'Limp to pit lane',
        description: 'Very slow lap, -3 laps down but technically still classified.',
        outcome: { speed_penalty: 5.0, classified: true, note: 'Limped back, classified finisher' },
        cardSynergy: ['recovery_mode'],
      },
    ],
  },
];

// ============================================================
// QUALIFYING EVENTS
// ============================================================
const QUALIFYING_EVENTS = [
  {
    id: 'qualifying_crash', name: 'Red Flag!',
    icon: '🔴', description: 'Red flag! Another car has crashed. Session suspended. You have one flying lap left.',
    choices: [
      {
        id: 'new_soft', label: 'New soft tyres',
        description: 'Fresh rubber guaranteed. But so are your rivals.',
        outcome: { quali_bonus: 0.3, note: 'New softs for flying lap' },
      },
      {
        id: 'keep_used', label: 'Keep used tyres',
        description: 'Already warmed up. Might be 0.1s faster in first sector.',
        outcome: { quali_bonus: 0.1, note: 'Used tyres but already prepped' },
      },
    ],
  },
  {
    id: 'yellow_flag', name: 'Yellow Flag!',
    icon: '🟡', description: 'A car has crashed ahead. Yellow flag, cannot push.',
    choices: [
      { id: 'abort_lap', label: 'Abort lap, prepare new run', outcome: { lap_aborted: true, fresh_run: true } },
      { id: 'continue_cautious', label: 'Continue at reduced pace', outcome: { time_penalty: 0.8 } },
    ],
  },
  {
    id: 'traffic', name: 'Traffic!',
    icon: '🚦', description: 'You caught a slow car on your hot lap!',
    choices: [
      { id: 'abort', label: 'Abort and go again', outcome: { lap_aborted: true, fresh_run: true } },
      { id: 'push_around', label: 'Push around them', outcome: { time_penalty: 0.5, risk: 0.1 } },
    ],
  },
  {
    id: 'perfect_conditions', name: 'Perfect Conditions!',
    icon: '☀️', description: 'Track is rubbered in perfectly. This is the moment.',
    choices: [
      { id: 'max_push', label: 'Absolute max attack', outcome: { time_bonus: 0.3, risk: 0.15 } },
      { id: 'measured', label: 'Measured hot lap', outcome: { time_bonus: 0.1 } },
    ],
  },
];

const POINTS_SYSTEM = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1];

// Teams are now defined in AI_TEAMS above (each entry includes player-usable fields)

const CARD_REWARDS = [
  ['undercut', 'overcut', 'push_mode', 'tyre_management_mode', 'sponsor_deal'],
  ['tire_wizard', 'safety_car_prep', 'brake_duct_upgrade', 'ers_deploy', 'bold_overtake'],
  ['engine_mode_push', 'rain_dance', 'safety_car_call', 'defensive_masterclass', 'recovery_mode'],
  ['qualifying_lap', 'double_stack', 'aggressive_strategy', 'wind_tunnel_data', 'pitstop_training'],
  ['engine_upgrade', 'reliability_package', 'data_analysis', 'wind_tunnel_data'],
];

const UPGRADES_SHOP = [
  { id: 'front_wing_update', name: 'Front Wing Update', cost: 8000, effect: { downforce: 3 }, description: '+3 Downforce' },
  { id: 'rear_wing_update', name: 'Rear Wing Update', cost: 7000, effect: { downforce: 2, speed: 1 }, description: '+2 Downforce, +1 Speed' },
  { id: 'engine_mode_unlock', name: 'Engine Mapping', cost: 10000, effect: { speed: 4 }, description: '+4 Speed' },
  { id: 'floor_upgrade', name: 'Floor Upgrade', cost: 12000, effect: { downforce: 4, speed: 1 }, description: '+4 Downforce, +1 Speed' },
  { id: 'suspension_tune', name: 'Suspension Rework', cost: 6000, effect: { reliability: 5 }, description: '+5 Reliability' },
  { id: 'pit_crew_training', name: 'Pit Crew Training', cost: 9000, effect: { pitSpeed: 8 }, description: '+8 Pit Speed' },
  { id: 'driver_fitness', name: 'Driver Fitness Program', cost: 5000, effect: { driver_skill: 3 }, description: '+3 to both drivers' },
  { id: 'data_systems', name: 'Data Analysis Systems', cost: 15000, effect: { strategy_vision: true }, description: 'See rival strategies' },
];
